import { StyleSheet } from 'react-native';
import { C } from '../constants/theme';
import { FONT } from '../constants/theme';

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.void, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 24 },
  corner: { position: 'absolute', width: 16, height: 16, borderColor: C.tealDim },
  cornerTL: { top: 16, left: 16,     borderTopWidth: 1,    borderLeftWidth: 1  },
  cornerTR: { top: 16, right: 16,    borderTopWidth: 1,    borderRightWidth: 1 },
  cornerBL: { bottom: 16, left: 16,  borderBottomWidth: 1, borderLeftWidth: 1  },
  cornerBR: { bottom: 16, right: 16, borderBottomWidth: 1, borderRightWidth: 1 },

  overlayBackdrop: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    width: '100%', height: '100%',
    backgroundColor: 'rgba(6,6,15,0.92)',
    justifyContent: 'center', paddingHorizontal: 24,
    zIndex: 9999, elevation: 9999,
  },

  unlockToast: { borderWidth: 1, borderColor: C.win+'cc', backgroundColor: 'rgba(6,78,59,0.97)', paddingVertical: 14, paddingHorizontal: 32, alignItems: 'center' },
  unlockToastText: { color: C.win, fontSize: 13, letterSpacing: 4, fontFamily: FONT, fontWeight: '700' },

  startContent:  { alignItems: 'center' },
  startTitle:    { fontSize: 72, fontWeight: '900', color: C.teal, letterSpacing: 16, fontFamily: FONT },
  startTitleSub: { fontSize: 36, fontWeight: '300', color: C.textSecond, letterSpacing: 24, marginTop: -12, fontFamily: FONT },
  startTagline:  { fontSize: 12, color: C.textDim, letterSpacing: 4, marginTop: 16, fontFamily: FONT },
  startDivider:  { width: 60, height: 1, backgroundColor: C.tealDim, marginVertical: 32 },
  startButton:   { borderWidth: 1, borderColor: C.teal, paddingVertical: 14, paddingHorizontal: 40 },
  startButtonText: { color: C.teal, fontSize: 13, letterSpacing: 6, fontFamily: FONT },
  devBtnRow:     { position: 'absolute', bottom: 36, flexDirection: 'row', alignSelf: 'center', gap: 10 },
  devResetBtn:   { borderWidth: 1, borderColor: '#ffff0066', paddingVertical: 6, paddingHorizontal: 16 },
  devResetBtnText: { color: '#ffff00aa', fontSize: 9, fontFamily: FONT, letterSpacing: 2 },

  screenTitle:    { fontSize: 28, fontWeight: '700', color: C.textPrimary, letterSpacing: 8, fontFamily: FONT, marginBottom: 4 },
  screenSubtitle: { fontSize: 10, color: C.textSecond, letterSpacing: 4, fontFamily: FONT, marginBottom: 12 },
  starTotalRow:   { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 14 },
  starTotalStar:  { fontSize: 14, color: C.star, textShadowColor: 'rgba(245,158,11,0.53)', textShadowRadius: 6 },
  starTotalText:  { fontSize: 10, color: 'rgba(245,158,11,0.8)', fontFamily: FONT, letterSpacing: 3 },

  menuButton:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '80%', borderWidth: 1, borderColor: C.borderBright, paddingVertical: 16, paddingHorizontal: 20, marginVertical: 6 },
  menuButtonLabel: { color: C.textPrimary, fontSize: 12, letterSpacing: 4, fontFamily: FONT },
  menuButtonArrow: { color: C.teal, fontSize: 20 },
  diffSub:         { color: C.textDim, fontSize: 9, letterSpacing: 2, fontFamily: FONT, marginTop: 3 },
  builderTaglineRow: { marginBottom: 20, alignItems: 'center' },
  builderTagline:    { color: C.textDim, fontSize: 9, letterSpacing: 2, fontFamily: FONT, textAlign: 'center', lineHeight: 16 },

  emptyState:     { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 },
  emptyStateIcon: { fontSize: 36, color: C.textDim, marginBottom: 4 },
  emptyStateText: { color: C.textSecond, fontSize: 13, letterSpacing: 4, fontFamily: FONT },
  emptyStateSub:  { color: C.textDim, fontSize: 9, letterSpacing: 2, fontFamily: FONT },

  savedLevelRow:     { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: C.border, backgroundColor: C.raised, paddingVertical: 10, paddingHorizontal: 14, marginBottom: 8 },
  savedLevelInfo:    { flex: 1, marginRight: 10 },
  savedLevelName:    { color: C.textPrimary, fontSize: 13, fontFamily: FONT, fontWeight: '700', letterSpacing: 2, marginBottom: 3 },
  savedLevelMeta:    { color: C.textDim, fontSize: 8, fontFamily: FONT, letterSpacing: 1 },
  savedLevelActions: { flexDirection: 'row', gap: 8 },
  savedLevelBtn:     { width: 36, height: 36, borderWidth: 1, justifyContent: 'center', alignItems: 'center' },
  savedLevelBtnText: { fontSize: 15 },

  editorHeaderRow:      { flexDirection: 'row', alignItems: 'center', width: '100%', marginBottom: 8 },
  editorTitle:          { fontSize: 16, fontWeight: '700', color: C.textPrimary, letterSpacing: 6, fontFamily: FONT },
  editorPlacingBar:     { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, paddingVertical: 7, paddingHorizontal: 14, marginBottom: 8 },
  editorPlacingBarLabel:{ color: C.textSecond, fontSize: 8, letterSpacing: 3, fontFamily: FONT },
  editorPlacingBarTile: { fontSize: 13, letterSpacing: 3, fontFamily: FONT, fontWeight: '700' },
  editorSettings:       { flex: 1, flexDirection: 'row', borderWidth: 1, borderColor: C.border, backgroundColor: C.raised },
  editorSetting:        { flex: 1, alignItems: 'center', paddingVertical: 6 },
  editorSettingLabel:   { color: C.textSecond, fontSize: 7, letterSpacing: 2, fontFamily: FONT, marginBottom: 3 },
  editorSettingDivider: { width: 1, backgroundColor: C.border },
  editorCounter:        { flexDirection: 'row', alignItems: 'center', gap: 3 },
  editorCounterBtn:     { width: 20, height: 20, borderWidth: 1, borderColor: C.borderBright, justifyContent: 'center', alignItems: 'center' },
  editorCounterBtnText: { color: C.textPrimary, fontSize: 13, lineHeight: 17, fontFamily: FONT },
  editorCounterValue:   { color: C.textPrimary, fontSize: 13, fontWeight: '700', fontFamily: FONT, minWidth: 16, textAlign: 'center' },
  editorGridArea:       { width: '100%', alignItems: 'center', marginBottom: 8 },
  editorGrid:           { borderWidth: 1, borderColor: C.border+'88' },
  editorFooterRow:      { flexDirection: 'row', gap: 8, marginTop: 6, width: '100%' },
  editorFooterBtnFlex:  { flex: 1, alignItems: 'center', justifyContent: 'center' },
  editorUtilRow:        { flexDirection: 'row', gap: 8, width: '100%', marginTop: 6, marginBottom: 6 },
  editorUtilBtn:        { flex: 1, borderWidth: 1, borderColor: C.borderBright, paddingVertical: 6, alignItems: 'center', justifyContent: 'center' },
  editorUtilBtnDisabled:{ opacity: 0.25 },
  editorUtilBtnText:    { color: C.textSecond, fontSize: 9, letterSpacing: 3, fontFamily: FONT },

  paletteWrapper:  { width: '100%', borderTopWidth: 1, borderColor: C.border, paddingTop: 6, marginBottom: 4 },
  paletteRow:      { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  paletteTile:     { flex: 1, marginHorizontal: 1, height: 52, borderWidth: 1, justifyContent: 'center', alignItems: 'center', gap: 2, paddingTop: 3 },
  paletteTileLabel:{ fontSize: 5, letterSpacing: 0.3, fontFamily: FONT, textAlign: 'center', lineHeight: 7 },

  levelNameInput: { borderWidth: 1, borderColor: 'rgba(0,212,200,0.53)', color: C.textPrimary, fontFamily: FONT, fontSize: 14, letterSpacing: 3, paddingHorizontal: 16, paddingVertical: 8, marginTop: 12, width: '100%', textAlign: 'center', backgroundColor: C.raised },
  levelNameHint:  { color: C.textDim, fontSize: 9, fontFamily: FONT, letterSpacing: 1, marginTop: 4 },
  saveParRow:      { flexDirection: 'row', alignItems: 'baseline', gap: 8, marginTop: 14, marginBottom: 6, width: '100%' },
  saveParLabel:    { color: C.textSecond, fontSize: 10, letterSpacing: 4, fontFamily: FONT },
  saveParSub:      { color: C.textDim, fontSize: 8, letterSpacing: 1, fontFamily: FONT },
  saveParControls: { flexDirection: 'row', alignItems: 'center', gap: 6, width: '100%' },
  saveParBtn:      { borderWidth: 1, borderColor: C.borderBright, width: 32, height: 32, justifyContent: 'center', alignItems: 'center' },
  saveParBtnText:  { color: C.textPrimary, fontSize: 14, fontFamily: FONT },
  saveParValueBox: { borderWidth: 1, borderColor: 'rgba(0,212,200,0.33)', backgroundColor: C.raised, paddingHorizontal: 18, paddingVertical: 4, alignItems: 'center' },
  saveParValue:    { color: C.teal, fontSize: 22, fontWeight: '700', fontFamily: FONT },
  saveParTurnLabel:{ color: 'rgba(0,212,200,0.53)', fontSize: 7, letterSpacing: 3, fontFamily: FONT },

  resetConfirm:        { width: '80%', borderWidth: 1, borderColor: C.warn, backgroundColor: C.warnDim, padding: 16, marginTop: 8, alignItems: 'center' },
  resetConfirmText:    { color: C.warn, fontSize: 11, letterSpacing: 3, fontFamily: FONT, marginBottom: 14 },
  resetConfirmRow:     { flexDirection: 'row', gap: 12 },
  resetConfirmBtn:     { borderWidth: 1, paddingVertical: 8, paddingHorizontal: 20 },
  resetConfirmBtnYes:  { borderColor: C.warn },
  resetConfirmBtnYesText: { color: C.warn, fontSize: 10, letterSpacing: 3, fontFamily: FONT },
  resetConfirmBtnNo:   { borderColor: C.textDim },
  resetConfirmBtnNoText:  { color: C.textSecond, fontSize: 10, letterSpacing: 3, fontFamily: FONT },

  levelScrollContent: { paddingHorizontal: 8, paddingTop: 8 },
  tierSection:  { marginBottom: 24 },
  tierHeader:   { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, paddingBottom: 8, marginBottom: 10 },
  tierDot:      { width: 5, height: 5, borderRadius: 3, marginRight: 10 },
  tierLabel:    { fontSize: 10, letterSpacing: 4, fontFamily: FONT, flexShrink: 1, flexGrow: 1 },
  tierCount:    { fontSize: 10, fontFamily: FONT },
  tierLockedBadge: { fontSize: 8, color: C.textDim, letterSpacing: 2, fontFamily: FONT, marginLeft: 8 },
  levelGrid:    { flexDirection: 'row', flexWrap: 'wrap' },
  levelSquare:        { width: 52, height: 52, borderWidth: 1, margin: 4, justifyContent: 'center', alignItems: 'center', backgroundColor: C.raised },
  levelSquareLocked:  { width: 52, height: 52, borderWidth: 1, margin: 4, justifyContent: 'center', alignItems: 'center', backgroundColor: C.locked, borderColor: C.lockedBorder },
  levelSquarePaywall: { width: 52, height: 52, borderWidth: 1, margin: 4, justifyContent: 'center', alignItems: 'center', backgroundColor: C.locked, borderColor: 'rgba(0,212,200,0.13)' },
  levelSquarePaywallLock: { fontSize: 18, color: C.teal+'44' },
  levelSquareText:     { fontSize: 16, fontWeight: '700', fontFamily: FONT },
  levelSquareCheck:    { fontSize: 15, fontWeight: '700', fontFamily: FONT },
  levelSquareNumSmall: { fontSize: 11, fontFamily: FONT, marginTop: -1 },
  levelSquareLock:     { fontSize: 14, color: C.lockedText },
  levelSquareStarRow:  { flexDirection: 'row', gap: 1, marginTop: 2 },
  levelSquareStar:     { fontSize: 8 },

  paywallBanner:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: 'rgba(0,212,200,0.4)', backgroundColor: 'rgba(0,144,122,0.13)', paddingVertical: 14, paddingHorizontal: 16, marginBottom: 20, marginHorizontal: 4 },
  paywallBannerLeft:   { flex: 1 },
  paywallBannerTitle:  { color: C.teal, fontSize: 12, letterSpacing: 4, fontFamily: FONT, fontWeight: '700', marginBottom: 3 },
  paywallBannerSub:    { color: 'rgba(0,212,200,0.53)', fontSize: 8, letterSpacing: 1, fontFamily: FONT },
  paywallBannerRight:  { alignItems: 'flex-end', marginLeft: 12 },
  paywallBannerPrice:  { color: C.teal, fontSize: 16, fontWeight: '700', fontFamily: FONT, letterSpacing: 2 },
  paywallBannerUnlock: { color: 'rgba(0,212,200,0.67)', fontSize: 9, letterSpacing: 3, fontFamily: FONT },

  unlockTerminal:      { width: '90%', borderWidth: 1, borderColor: C.teal, backgroundColor: C.raised },
  unlockTerminalBar:   { backgroundColor: 'rgba(0,212,200,0.13)', borderBottomWidth: 1, borderBottomColor: C.teal+'44', paddingVertical: 6, paddingHorizontal: 14 },
  unlockTerminalBarText:{ color: C.teal, fontSize: 9, letterSpacing: 4, fontFamily: FONT },
  unlockBody:          { padding: 20, alignItems: 'center' },
  unlockIcon:          { fontSize: 48, color: C.teal, marginBottom: 10 },
  unlockTitle:         { color: C.textPrimary, fontSize: 22, fontWeight: '700', fontFamily: FONT, letterSpacing: 6, marginBottom: 2 },
  unlockSubtitle:      { color: C.warn, fontSize: 9, letterSpacing: 6, fontFamily: FONT, marginBottom: 12 },
  unlockDivider:       { width: '100%', height: 1, backgroundColor: C.border, marginVertical: 14 },
  unlockDesc:          { color: C.textSecond, fontSize: 10, letterSpacing: 1, fontFamily: FONT, textAlign: 'center', lineHeight: 17, marginBottom: 14 },
  unlockFeatureList:   { width: '100%', gap: 8, marginBottom: 4 },
  unlockFeatureRow:    { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  unlockFeatureDash:   { color: 'rgba(0,212,200,0.4)', fontSize: 10, fontFamily: FONT, marginTop: 1 },
  unlockFeatureText:   { color: C.textPrimary, fontSize: 10, letterSpacing: 1, fontFamily: FONT, lineHeight: 16, flexShrink: 1 },
  unlockBuyBtn:        { width: '100%', borderWidth: 1, borderColor: C.teal, backgroundColor: C.tealDim+'44', paddingVertical: 14, alignItems: 'center', marginBottom: 10 },
  unlockBuyBtnText:    { color: C.teal, fontSize: 13, letterSpacing: 5, fontFamily: FONT, fontWeight: '700' },
  unlockRestoreBtn:    { paddingVertical: 6, paddingHorizontal: 12 },
  unlockRestoreBtnText:{ color: C.textDim, fontSize: 9, letterSpacing: 3, fontFamily: FONT },

  backButton:           { marginTop: 12, paddingVertical: 8, paddingHorizontal: 16 },
  backButtonText:       { color: C.textSecond, fontSize: 11, letterSpacing: 3, fontFamily: FONT },
  resetProgressBtnText: { color: C.textSecond, fontSize: 11, letterSpacing: 3, fontFamily: FONT },

  gameHeader:      { flexDirection: 'row', alignItems: 'baseline', marginBottom: 12 },
  gameLevelLabel:  { color: C.textSecond, fontSize: 10, letterSpacing: 4, fontFamily: FONT, marginRight: 8 },
  gameLevelNumber: { color: C.textPrimary, fontSize: 28, fontWeight: '700', fontFamily: FONT },
  readout:         { flexDirection: 'row', borderWidth: 1, borderColor: C.border, marginBottom: 8, backgroundColor: C.raised },
  readoutCell:     { paddingHorizontal: 18, paddingVertical: 8, alignItems: 'center' },
  readoutDivider:  { width: 1, backgroundColor: C.border },
  readoutLabel:    { color: C.textSecond, fontSize: 8, letterSpacing: 2, fontFamily: FONT },
  readoutValue:    { color: C.textPrimary, fontSize: 20, fontWeight: '700', fontFamily: FONT, marginTop: 2 },
  readoutParCell:  { borderWidth: 1, borderColor: 'rgba(245,158,11,0.4)', backgroundColor: 'rgba(120,53,15,0.2)', marginVertical: 4, marginRight: 4, paddingHorizontal: 14 },
  readoutParValue: { color: C.hint },

  echoIndicator:     { borderWidth: 1, paddingHorizontal: 16, paddingVertical: 4, marginBottom: 8, minWidth: 140, alignItems: 'center' },
  echoIndicatorText: { color: C.echo, fontSize: 10, letterSpacing: 3, fontFamily: FONT },
  gridOuter:     { alignSelf: 'stretch', alignItems: 'center', marginVertical: 12, position: 'relative' },
  gridContainer: { borderWidth: 1, borderColor: C.border },
  bannerOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 16 },

  alertBanner:  { borderWidth: 1, borderLeftWidth: 5, borderColor: C.warn, backgroundColor: 'rgba(127,29,46,0.97)' },
  winBanner:    { borderWidth: 1, borderLeftWidth: 5, borderColor: C.win,  backgroundColor: 'rgba(6,78,59,0.97)'   },
  hintBanner:   { borderWidth: 1, borderLeftWidth: 5, borderColor: C.hint, backgroundColor: 'rgba(120,53,15,0.97)' },
  alertBar:     { display: 'none' },
  alertContent: { padding: 14, alignItems: 'center', alignSelf: 'stretch' },
  alertTitle:   { color: C.warn, fontSize: 12, letterSpacing: 4, fontFamily: FONT, fontWeight: '700', marginBottom: 4, textAlign: 'center' },
  alertReason:  { color: C.textSecond, fontSize: 10, letterSpacing: 2, fontFamily: FONT, marginBottom: 12, textAlign: 'center' },
  alertButton:  { borderWidth: 1, borderColor: C.warn, paddingVertical: 10, alignItems: 'center', justifyContent: 'center' },
  alertButtonText: { color: C.warn, fontSize: 10, letterSpacing: 3, fontFamily: FONT, textAlign: 'center' },
  winTurnsText:    { color: C.win+'aa', fontSize: 9, letterSpacing: 3, fontFamily: FONT, marginBottom: 12, marginTop: 2 },
  winStarLabel:    { color: 'rgba(245,158,11,0.8)', fontSize: 9, letterSpacing: 4, fontFamily: FONT, marginBottom: 6 },
  winStatsRow:     { flexDirection: 'row', borderWidth: 1, borderColor: 'rgba(16,185,129,0.27)', backgroundColor: 'rgba(6,78,59,0.4)', marginBottom: 12, marginTop: 2 },
  winStatCell:     { paddingHorizontal: 20, paddingVertical: 6, alignItems: 'center' },
  winStatLabel:    { color: C.textSecond, fontSize: 7, letterSpacing: 2, fontFamily: FONT },
  winStatValue:    { color: C.textPrimary, fontSize: 18, fontWeight: '700', fontFamily: FONT, marginTop: 1 },
  winStatDivider:  { width: 1, backgroundColor: 'rgba(16,185,129,0.27)' },
  winButtonRow:    { flexDirection: 'row', gap: 8, alignItems: 'stretch', justifyContent: 'center', marginTop: 4, alignSelf: 'stretch' },
  rowBtn:          { flex: 1, borderWidth: 1, borderColor: C.warn, paddingVertical: 10, alignItems: 'center', justifyContent: 'center' },
  winRetryBtn:     { flex: 1, borderWidth: 1, borderColor: C.win, backgroundColor: C.winDim, paddingVertical: 10, alignItems: 'center', justifyContent: 'center' },
  winRetryBtnText: { color: C.win, fontSize: 10, letterSpacing: 3, fontFamily: FONT, textAlign: 'center' },
  hintAwardedBadge:{ borderWidth: 1, borderColor: 'rgba(245,158,11,0.4)', backgroundColor: 'rgba(120,53,15,0.2)', paddingVertical: 4, paddingHorizontal: 14, marginBottom: 10 },
  hintAwardedText: { color: C.hint, fontSize: 9, letterSpacing: 3, fontFamily: FONT },
  hintBodyText:    { color: C.textPrimary, fontSize: 14, letterSpacing: 3, fontFamily: FONT, textAlign: 'center', marginVertical: 10, lineHeight: 22 },
  hintSubText:     { color: 'rgba(245,158,11,0.67)', fontSize: 9, letterSpacing: 3, fontFamily: FONT, marginBottom: 10 },
  hintArrowRow:    { flexDirection: 'row', alignItems: 'center', gap: 8, marginVertical: 12 },
  hintArrowBox:    { width: 44, height: 44, borderWidth: 1, borderColor: C.hint+'99', backgroundColor: C.hintDim+'66', justifyContent: 'center', alignItems: 'center' },
  hintArrowText:   { fontSize: 22, color: C.hint },
  hintArrowSep:    { color: C.hint+'55', fontSize: 14, fontFamily: FONT },

  dpad:         { alignItems: 'center', marginTop: 4 },
  dpadBtn:      { width: 52, height: 52, margin: 3, borderWidth: 1, borderColor: C.borderBright, backgroundColor: C.raised, justifyContent: 'center', alignItems: 'center' },
  dpadDisabled: { opacity: 0.2 },
  dpadGap:      { width: 52, margin: 3 },
  dpadText:     { fontSize: 18, color: C.textPrimary },
  dpadUtilBtn:  { width: 58, height: 58, margin: 3, borderWidth: 1, justifyContent: 'center', alignItems: 'center', flexDirection: 'column', gap: 3 },
  utilRow:           { flexDirection: 'row', gap: 10, marginTop: 10, marginBottom: 2 },
  utilBtn:           { flexDirection: 'row', alignItems: 'center', borderWidth: 1, paddingVertical: 8, paddingHorizontal: 18, gap: 7 },
  undoBtn:           { borderColor: C.borderBright, backgroundColor: C.raised },
  hintBtn:           { borderColor: 'rgba(245,158,11,0.4)', backgroundColor: 'rgba(120,53,15,0.27)' },
  utilBtnDisabled:   { opacity: 0.25 },
  utilBtnIcon:       { fontSize: 14, color: C.textPrimary },
  utilIconDisabled:  { color: C.textDim },
  utilBtnLabel:      { fontSize: 9, letterSpacing: 3, fontFamily: FONT, color: C.textSecond, textAlign: 'center' },
  utilLabelDisabled: { color: C.textDim },

  footerRow:    { flexDirection: 'row', marginTop: 12, gap: 12 },
  footerBtn:    { borderWidth: 1, borderColor: C.border, paddingVertical: 7, paddingHorizontal: 16 },
  footerBtnText:{ color: C.textSecond, fontSize: 9, letterSpacing: 3, fontFamily: FONT },

  tutorialBanner:  { borderWidth: 1, borderColor: '#94a3b8', backgroundColor: 'rgba(15,21,32,0.93)', borderLeftWidth: 5, width: 300 },
  tutorialTitle:   { color: '#94a3b8', fontSize: 12, letterSpacing: 4, fontFamily: FONT, fontWeight: '700', marginBottom: 14, textAlign: 'center' },
  tutorialLines:   { marginBottom: 18, alignSelf: 'stretch' },
  tutorialLineRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  tutorialBullet:  { color: '#94a3b8', fontSize: 11, fontFamily: FONT, lineHeight: 18, width: 18, flexShrink: 0 },
  tutorialLineText:{ color: C.textPrimary, fontSize: 11, fontFamily: FONT, letterSpacing: 1, lineHeight: 18, flexShrink: 1 },
  tutorialDismissRow: { flexDirection: 'row', gap: 12, alignSelf: 'center', alignItems: 'center' },
  tutorialDismiss: { borderWidth: 1, borderColor: '#94a3b8', paddingVertical: 8, paddingHorizontal: 24 },
  tutorialSkip:    { borderWidth: 1, borderColor: 'rgba(100,116,139,0.33)', paddingVertical: 8, paddingHorizontal: 16 },
  tutorialSkipText:    { color: '#64748b', fontSize: 11, letterSpacing: 3, fontFamily: FONT },
  tutorialDismissText: { color: '#94a3b8', fontSize: 11, letterSpacing: 4, fontFamily: FONT },
  parMsgBody:      { alignItems: 'center', alignSelf: 'center', marginBottom: 16, borderWidth: 1, borderColor: 'rgba(148,163,184,0.27)', paddingVertical: 12, paddingHorizontal: 32, backgroundColor: 'rgba(255,255,255,0.03)' },
  parMsgParNum:    { color: '#e2e8f0', fontSize: 52, fontWeight: '700', fontFamily: FONT, lineHeight: 58 },
  parMsgParLabel:  { color: '#94a3b8', fontSize: 10, letterSpacing: 4, fontFamily: FONT, marginTop: -4 },
});

export default styles;
